"""Voqi agent server — a minimal FastAPI host for the Pipecat voice agent.

The widget POSTs to ``/start`` with a session id and the host-app's tool
schema; this server provisions a Daily WebRTC room and kicks off the
agent loop in-process. Auth is purely origin-based — set
``VOQI_ALLOWED_ORIGINS`` to your host domains and the browser will
refuse to talk to this server from anywhere else. No JWTs, no DB, no
control-plane HTTP. All agent configuration (prompt, persona, knowledge
base) comes from ``voqi.config.yaml`` on this machine.

For production (autoscale, multi-tenant, hosted control plane), see
the managed Aelios AI offering at https://aeliosai.com.
"""

import argparse
import asyncio
import os
import sys
import uuid
from contextlib import asynccontextmanager
from typing import Optional

import aiohttp
import uvicorn
from dotenv import load_dotenv
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from loguru import logger
from pipecat.runner.types import DailyRunnerArguments, RunnerArguments

_bot_module = None


def _get_bot_module():
    import importlib.util

    main_module = sys.modules["__main__"]
    if hasattr(main_module, "bot"):
        return main_module

    try:
        import bot
        return bot
    except ImportError:
        pass

    cwd = os.getcwd()
    for filename in os.listdir(cwd):
        if filename.endswith(".py") and filename != "server.py":
            try:
                module_name = filename[:-3]
                spec = importlib.util.spec_from_file_location(
                    module_name, os.path.join(cwd, filename)
                )
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                if hasattr(module, "bot"):
                    return module
            except Exception as e:
                print(f"Error loading module {filename}: {e}")
                continue

    raise ImportError(
        "Could not find a 'bot' function. Make sure bot.py exposes one."
    )


def _preload_bot_module():
    global _bot_module
    if _bot_module is None:
        _bot_module = _get_bot_module()
    return _bot_module


_preload_bot_module()
load_dotenv(override=True)

MAXIMUM_SESSION_DURATION_MINUTES = int(
    os.getenv("MAXIMUM_SESSION_DURATION_MINUTES", "100")
)

# Origin allowlist — the only auth surface between widget and agent
# server. Browsers send ``Origin`` automatically on cross-origin POSTs
# and respect the CORS allow-list the server hands back, so a widget
# embedded on an unlisted domain physically cannot reach /start. No
# tokens, no secrets to coordinate.
#
# Comma-separated list of origins (e.g. ``https://app.example.com``),
# or ``*`` for open dev mode. Default is ``*`` so localhost just works;
# set this explicitly in production.
ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv("VOQI_ALLOWED_ORIGINS", "*").split(",")
    if o.strip()
]

_bot_task: Optional[asyncio.Task] = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.session = aiohttp.ClientSession()
    yield
    await app.state.session.close()


def create_server_app() -> FastAPI:
    app = FastAPI(lifespan=lifespan)

    app.add_middleware(
        CORSMiddleware,
        allow_origins=ALLOWED_ORIGINS,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.post("/start")
    async def start_agent(request: Request):
        """Start a Voqi voice session.

        Expected POST body::

            {
                "createDailyRoom": true,
                "dailyRoomProperties": { "start_video_off": true },
                "dailyMeetingTokenProperties": { "is_owner": true, "user_name": "Bot" },
                "body": {
                    "session_uuid": "<uuid generated by widget>",
                    "tools": [ ... widget-supplied tool schemas ... ],
                    "language": "en",
                    "mode": "action"
                }
            }
        """
        global _bot_task

        try:
            request_data = await request.json()
            logger.debug(f"Received request: {request_data}")
        except Exception as e:
            logger.error(f"Failed to parse request body: {e}")
            request_data = {}

        create_daily_room = request_data.get("createDailyRoom", False)
        body = request_data.get("body", {})
        daily_room_properties_dict = request_data.get("dailyRoomProperties", None)
        daily_token_properties_dict = request_data.get("dailyMeetingTokenProperties", None)

        # Mint a session_uuid if the widget didn't supply one.
        body.setdefault("session_uuid", str(uuid.uuid4()))

        try:
            result = None
            runner_args = None

            if create_daily_room or os.getenv("DAILY_SAMPLE_ROOM_URL"):
                from pipecat.runner.daily import configure
                from pipecat.transports.daily.utils import (
                    DailyMeetingTokenProperties,
                    DailyRoomProperties,
                )

                room_properties = None
                if daily_room_properties_dict:
                    try:
                        room_properties = DailyRoomProperties(**daily_room_properties_dict)
                    except Exception as e:
                        logger.error(f"Failed to parse dailyRoomProperties: {e}")

                token_properties = None
                if daily_token_properties_dict:
                    try:
                        token_properties = DailyMeetingTokenProperties(**daily_token_properties_dict)
                    except Exception as e:
                        logger.error(f"Failed to parse dailyMeetingTokenProperties: {e}")

                async with aiohttp.ClientSession() as session:
                    room_url, token = await configure(
                        session,
                        room_properties=room_properties,
                        token_properties=token_properties,
                    )

                runner_args = DailyRunnerArguments(room_url=room_url, token=token, body=body)
                result = {
                    "dailyRoom": room_url,
                    "dailyToken": token,
                    "sessionId": body["session_uuid"],
                }
            else:
                runner_args = RunnerArguments(body=body)

            async def run_and_cleanup():
                global _bot_task
                try:
                    bot_module = _get_bot_module()
                    await asyncio.wait_for(
                        bot_module.bot(runner_args),
                        timeout=MAXIMUM_SESSION_DURATION_MINUTES * 60,
                    )
                except asyncio.TimeoutError:
                    logger.warning(
                        f"Session exceeded {MAXIMUM_SESSION_DURATION_MINUTES} minutes, terminating"
                    )
                except Exception as e:
                    logger.error(f"Bot error: {e}")
                finally:
                    _bot_task = None

            logger.info("Starting bot in-process")
            _bot_task = asyncio.create_task(run_and_cleanup())

            return result

        except Exception as e:
            logger.error(f"Error starting call: {e}")
            return JSONResponse(content={"error": str(e)}, status_code=500)

    return app


def main():
    parser = argparse.ArgumentParser(description="Voqi agent server")
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=3002)
    parser.add_argument("--verbose", "-v", action="count", default=0)

    args = parser.parse_args()

    print()
    print("🎙️  Voqi agent server ready!")
    print(f"   → POST http://{args.host}:{args.port}/start to begin a session")
    print(f"   → Allowed origins: {', '.join(ALLOWED_ORIGINS)}")
    print()

    app = create_server_app()
    uvicorn.run(app, host=args.host, port=args.port)


if __name__ == "__main__":
    main()
